ci:
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks

    For more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: 'chore/pre-commit-autoupdate'
  autoupdate_commit_msg: 'chore: pre-commit automatic update'
  autoupdate_schedule: weekly

repos:

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.9 # v0.14.1
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: "^examples/.*_.*"
      - id: ruff-format
        #exclude: "^src|^tests|^examples/.*_.*"

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.18.0 # 1.18.0
    hooks:
      - id: zizmor
        args: ["--pedantic"]

  # NOTE: Ruff does not check for python code in some part of the documentation,
  # e.g. python code block, ..., see https://github.com/astral-sh/ruff/issues/8237
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.20.0 # 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==25.1.0]
        args: ["--line-length=88"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: ["tomli"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        # args not working with pyproject.toml
        args: [
            -lll,
            -n, "3",
            -r,
            -x, "venv/*, tests/*"
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        additional_dependencies: ["types-PyYAML"]
        # Exclude only works here, not in config files
        exclude: "tests/|doc/|benchmarks/|examples"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: check-yaml
    - id: trailing-whitespace
      exclude: "tests/benchmarks"
    - id: check-added-large-files
    - id: check-case-conflict
