[tool.poetry]
name = "ansys-chemkin"
version = "0.25.dev10"
description = "PyChemkin provides Pythonic interface to Ansys chemkin utilities and reactor models"
license = "MIT"
authors = ["ANSYS, Inc. <ansys.support@ansys.com>"]
maintainers = ["PyAnsys developers <pyansys.maintainers@ansys.com>"]
readme = "README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Natural Language :: English",
]
packages = [
	{include = "chemkin", from = "ansys"},
]

[tool.poetry.dependencies]
python = ">=3.9"
numpy= ">=1.14.0"
pyyaml = ">=6.0"

[tool.poetry.group.test.dependencies]
pytest = "*"
pytest-cov = "*"

[tool.poetry.group.test]
optional = true

[doc.poetry.dependencies]
nbsphinx= ">=0.9.3"
notebook= ">=7.0.5"
sphinx= ">=7.2.5"
sphinx-autoapi= ">=3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = "88"

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = "88"
src_paths = ["ansys", "tests"]

[tool.codespell]
ignore-words-list = "delt, pres, te"
quiet-level = 3
skip = "*.toml,*.pyc,*.xml,*.gif,*.png,*.jpg,*.js,*.html,*.svg,*.asc,*.out"
