name: Github CI

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  DOCUMENTATION_CNAME: 'chemkin.docs.pyansys.com'
  MAIN_PYTHON_VERSION: '3.10'
  PACKAGE_NAME: 'ansys-chemkin'
  PACKAGE_NAMESPACE: 'ansys.chemkin'
  CHEMKIN_IMAGE: 'ghcr.io/ansys/chemkin'
  POETRY_VIRTUALENVS_CREATE: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code-style:
    name: "Code style"
    runs-on: windows-latest
    steps:
      - uses: ansys/actions/code-style@v10
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  doc-style:
    name: "Doc style"
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/doc-style@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  smoke-tests:
    name: "Wheelhouse for ${{ matrix.os }} and ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    needs: code-style
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.10', '3.11', '3.12']
        should-release:
          - ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags') }}
    steps:
      - name: Build wheelhouse and perform smoke test
        uses: ansys/actions/build-wheelhouse@v10
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          library-namespace: ${{ env.PACKAGE_NAMESPACE }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

  tests:
    name: "Test ${{ matrix.python-version }} with ubuntu"
    needs: [smoke-tests]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ansys/chemkin
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --cpus 1 --user root
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - name: Run pytest
        uses: ansys/actions/tests-pytest@v10
        env:
          ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
          POETRY_VIRTUALENVS_CREATE: 'false'
        with:
          python-version: ${{ matrix.python-version }}
          requires-xvfb: false
          use-python-cache: false

      - uses: codecov/codecov-action@v5
        name: 'Upload coverage to CodeCov'

  doc:
    name: "Doc build"
    runs-on: ubuntu-latest
    needs: doc-style
    steps:
      - uses: actions/checkout@v6
      - uses: pandoc/actions/setup@v1
      - name: Install libjpeg
        run: sudo apt-get -y install libjpeg-dev
      - name: Run Ansys documentation building action
        uses: ansys/actions/doc-build@v10
        env:
          ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
        with:
          sphinxopts: '-j auto'
          add-pdf-html-docs-as-assets: true
          check-links: false

  build-library:
    name: "Build library"
    needs: [doc, tests]
    runs-on: windows-latest
    steps:
      - uses: ansys/actions/build-library@v10
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  doc-deploy-dev:
    name: "Deploy development documentation"
    # Deploy development only when merging to main
    if: github.ref == 'refs/heads/main'
    needs: build-library
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy the latest documentation"
        uses: ansys/actions/doc-deploy-dev@v10
        with:
            cname: ${{ env.DOCUMENTATION_CNAME }}
            token: ${{ secrets.GITHUB_TOKEN }}
            bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
            bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  release:
    name: Release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build-library
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication with PyPI
      contents: write # Required for OIDC authentication with PyPI
      attestations: write # Write attestation for uploaded distribution artifacts
    steps:

      - name: "Download the library artifacts from build-library step"
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: ${{ env.PACKAGE_NAME }}-artifacts
          path: ${{ env.PACKAGE_NAME }}-artifacts

      - name: "Upload artifacts to PyPI using trusted publisher"
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: "https://upload.pypi.org/legacy/"
          print-hash: true
          packages-dir: ${{ env.PACKAGE_NAME }}-artifacts
          skip-existing: false

      - name: "Release to GitHub"
        uses: ansys/actions/release-github@eb7d0fc873deeee6d4740774675ce1741cb6f154 # v10.2.2
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog-release-notes: true
          only-code: true
          add-artifact-attestation-notes: true
          generate_release_notes: false

  doc-deploy-stable:
    name: "Deploy stable documentation"
    # Deploy release documentation when creating a new tag
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: windows-latest
    needs: release
    steps:
      - name: "Deploy the stable documentation"
        uses: ansys/actions/doc-deploy-stable@v10
        with:
            cname: ${{ env.DOCUMENTATION_CNAME }}
            token: ${{ secrets.GITHUB_TOKEN }}


