name: Container Test

on:
  workflow_dispatch:
#  pull_request:
#  push:
#    tags:
#      - "*"
#    branches:
#      - main

env:
  DOCUMENTATION_CNAME: 'chemkin.docs.pyansys.com'
  MAIN_PYTHON_VERSION: '3.10'
  PACKAGE_NAME: 'ansys-chemkin'
  PACKAGE_NAMESPACE: 'ansys.chemkin'
  ANSYS251_DIR: 'C:\Program Files\ANSYS Inc\v251\'
  CHEMKIN_IMAGE: 'ghcr.io/ansys/chemkin'
  POETRY_VIRTUALENVS_CREATE: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke-tests:
    name: "Wheelhouse for ${{ matrix.os }} and ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']
        should-release:
          - ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags') }}
    steps:
      - name: Build wheelhouse and perform smoke test
        uses: ansys/actions/build-wheelhouse@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          library-namespace: ${{ env.PACKAGE_NAMESPACE }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

  tests:
    name: "Test ${{ matrix.python-version }} with ${{ matrix.os }}"
    needs: [smoke-tests]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ansys/chemkin
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        ANSYS251_DIR: 'C:\Program Files\ANSYS Inc\v251\'
      ports:
        - 80
      options: --cpus 1
    steps:
      - name: Run pytest
        uses: ansys/actions/tests-pytest@v4
        env:
          ANSYSLMD_LICENSE_FILE: ${{ format('1055@{0}', secrets.LICENSE_SERVER) }}
          POETRY_VIRTUALENVS_CREATE: 'false'
          ANSYS251_DIR: 'C:\Program Files\ANSYS Inc\v251\'
        with:
          python-version: 3.10
          requires-xvfb: false

      - uses: codecov/codecov-action@v3
        name: 'Upload coverage to CodeCov'

  build-library:
    name: "Build library"
    needs: [tests]
    runs-on: windows-latest
    steps:
      - uses: ansys/actions/build-library@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
